name: ProjectX2_fuzzer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ProjectX2-main
        
    steps:
    - uses: actions/checkout@v4
    - name: Build docker container
      run: 
        ./build.sh
        
    -name: Run the container
      run:
        ./run.sh
